"""empty message

Revision ID: 059a496f4f85
Revises: c06d174dfa3a
Create Date: 2022-05-03 16:19:43.723333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059a496f4f85'
down_revision = 'c06d174dfa3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_word', sa.Column('accuracy', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predicted_word', 'accuracy')
    # ### end Alembic commands ###
