"""empty message

Revision ID: 165323a63d70
Revises: e47cc2864401
Create Date: 2022-04-23 22:05:11.948255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '165323a63d70'
down_revision = 'e47cc2864401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('predict_id', table_name='users_predicted_words')
    op.drop_column('users_predicted_words', 'predict_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_predicted_words', sa.Column('predict_id', mysql.VARCHAR(length=80), nullable=True))
    op.create_index('predict_id', 'users_predicted_words', ['predict_id'], unique=False)
    # ### end Alembic commands ###
