"""empty message

Revision ID: 17a40a04242c
Revises: 55dfe1d37d3d
Create Date: 2022-05-02 10:00:58.022662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a40a04242c'
down_revision = '55dfe1d37d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_word', sa.Column('accuracy', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predicted_word', 'accuracy')
    # ### end Alembic commands ###
