"""empty message

Revision ID: 23ee38d70b49
Revises: e3a664f29239
Create Date: 2022-04-23 22:20:44.272337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23ee38d70b49'
down_revision = 'e3a664f29239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_predicted_words_ibfk_1', 'users_predicted_words', type_='foreignkey')
    op.drop_column('users_predicted_words', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_predicted_words', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_predicted_words_ibfk_1', 'users_predicted_words', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
