"""empty message

Revision ID: 2e287a602094
Revises: 4ec409a0772e
Create Date: 2022-06-23 18:57:19.279754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e287a602094'
down_revision = '4ec409a0772e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommended_phrases', sa.Column('emotion', sa.Enum('anger', 'annoyed', 'disgust', 'fear', 'joy', 'others', 'outraged', 'sadness', 'strong', 'upset', name='emotionsenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommended_phrases', 'emotion')
    # ### end Alembic commands ###
