"""empty message

Revision ID: 4ec409a0772e
Revises: fed67a1de016
Create Date: 2022-06-23 18:56:27.001995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ec409a0772e'
down_revision = 'fed67a1de016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommended_phrases', 'emotion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommended_phrases', sa.Column('emotion', mysql.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
