"""empty message

Revision ID: 55dfe1d37d3d
Revises: b154bf5a83d1
Create Date: 2022-05-02 06:45:00.483254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55dfe1d37d3d'
down_revision = 'b154bf5a83d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predicted_word', 'accuracy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_word', sa.Column('accuracy', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
