"""empty message

Revision ID: 5a5fe14ecd4f
Revises: d264882c86cb
Create Date: 2022-04-23 19:14:14.317036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5fe14ecd4f'
down_revision = 'd264882c86cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_word', sa.Column('accuracy', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predicted_word', 'accuracy')
    # ### end Alembic commands ###
