"""empty message

Revision ID: 9f58b47fb8b1
Revises: cb42f703e5ea
Create Date: 2022-04-23 19:14:54.898994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f58b47fb8b1'
down_revision = 'cb42f703e5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_word', sa.Column('word', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predicted_word', 'word')
    # ### end Alembic commands ###
