"""empty message

Revision ID: b154bf5a83d1
Revises: c45d792b2f23
Create Date: 2022-04-23 23:25:28.643733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b154bf5a83d1'
down_revision = 'c45d792b2f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('predicted_word_ibfk_1', 'predicted_word', type_='foreignkey')
    op.create_foreign_key(None, 'predicted_word', 'users_predicted_words', ['users_predicted_words_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predicted_word', type_='foreignkey')
    op.create_foreign_key('predicted_word_ibfk_1', 'predicted_word', 'users_predicted_words', ['users_predicted_words_id'], ['id'])
    # ### end Alembic commands ###
