"""empty message

Revision ID: c06d174dfa3a
Revises: 17a40a04242c
Create Date: 2022-05-03 16:19:27.547129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c06d174dfa3a'
down_revision = '17a40a04242c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predicted_word', 'accuracy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_word', sa.Column('accuracy', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
