"""empty message

Revision ID: c45d792b2f23
Revises: 23ee38d70b49
Create Date: 2022-04-23 22:21:39.626386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45d792b2f23'
down_revision = '23ee38d70b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_predicted_words', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('users_predicted_words', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users_predicted_words', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'users_predicted_words', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_predicted_words', type_='foreignkey')
    op.drop_column('users_predicted_words', 'updated_at')
    op.drop_column('users_predicted_words', 'created_at')
    op.drop_column('users_predicted_words', 'user_id')
    # ### end Alembic commands ###
