"""empty message

Revision ID: cb42f703e5ea
Revises: 5a5fe14ecd4f
Create Date: 2022-04-23 19:14:40.212118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb42f703e5ea'
down_revision = '5a5fe14ecd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predicted_word', 'word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_word', sa.Column('word', sa.VARCHAR(length=80), nullable=False))
    # ### end Alembic commands ###
