"""empty message

Revision ID: e3a664f29239
Revises: 165323a63d70
Create Date: 2022-04-23 22:10:50.128703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a664f29239'
down_revision = '165323a63d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_predicted_words', sa.Column('predict_id', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'users_predicted_words', ['predict_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_predicted_words', type_='unique')
    op.drop_column('users_predicted_words', 'predict_id')
    # ### end Alembic commands ###
