"""empty message

Revision ID: e47cc2864401
Revises: 4e032ff38bb2
Create Date: 2022-04-23 21:51:15.065765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47cc2864401'
down_revision = '4e032ff38bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_word', sa.Column('users_predicted_words_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'predicted_word', 'users_predicted_words', ['users_predicted_words_id'], ['id'])
    op.add_column('users_predicted_words', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_predicted_words', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_predicted_words', type_='foreignkey')
    op.drop_column('users_predicted_words', 'user_id')
    op.drop_constraint(None, 'predicted_word', type_='foreignkey')
    op.drop_column('predicted_word', 'users_predicted_words_id')
    # ### end Alembic commands ###
