"""empty message

Revision ID: fed67a1de016
Revises: 059a496f4f85
Create Date: 2022-06-23 18:26:45.913612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed67a1de016'
down_revision = '059a496f4f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommended_phrases')
    # ### end Alembic commands ###
